# -*- coding: utf-8 -*-
"""Text to Image Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uhx1x2vrgsDyk-kSPtrBbnD7xfMtYnm

* Task-02: Image Generation using Pre-trained Model (Stable Diffusion)
"""

!pip install diffusers --upgrade
!pip install invisible_watermark transformers accelerate safetensors gradio

from diffusers import DiffusionPipeline
import torch
import gradio as gr
import matplotlib.pyplot as plt

"""* **Step 3: Initializing base pipeline **"""

pipe = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
)

pipe.to("cuda")

"""* Defining Functions for gradio

"""

def generate_image(prompt, negative_prompt=""):
    # Generate image using the pipeline
    image = pipe(prompt=prompt, negative_prompt=negative_prompt).images[0]
    return image

"""* Creating Interface"""

iface = gr.Interface(
    fn=generate_image,
    inputs=[
        gr.Textbox(lines=2, placeholder="Enter your image description...", label="Prompt"),
        gr.Textbox(lines=1, placeholder="(Optional) Things to avoid...", label="Negative Prompt")
    ],
    outputs=gr.Image(type="pil"),
    title="🖼️ Stable Diffusion XL Image Generator",
    description="Enter a text prompt to generate AI-based images using Stable Diffusion XL."
)

"""* Launching App"""

iface.launch()